version: "3"

services:
  atlas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 21000:21000
    container_name: atlas
    restart: unless-stopped
    hostname: atlas
    volumes:
      - atlas_conf:/apache-atlas/conf
      - atlas_data:/apache-atlas/data
      - atlas_logs:/apache-atlas/logs
      - hadoop_srcfolder:/opt/hadoop-3.2.1
    # networks:
    #   - default

  hive:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    container_name: hive
    restart: unless-stopped
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    # networks:
    #   - default

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: unless-stopped
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_srcfolder:/opt/hadoop-3.2.1
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    # networks:
    #   - default

  datanode_0:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode_0
    restart: unless-stopped
    volumes:
      - hadoop_datanode_0:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    # networks:
    #   - default

  # datanode_1:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode_1
  #   restart: unless-stopped
  #   volumes:
  #     - hadoop_datanode_1:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #   env_file:
  #     - ./hadoop.env
  #   # networks:
  #   #   - default

  # datanode_2:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode_2
  #   restart: unless-stopped
  #   volumes:
  #     - hadoop_datanode_2:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #   env_file:
  #     - ./hadoop.env
  #   # networks:
  #   #   - default

  # datanode_3:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode_3
  #   restart: unless-stopped
  #   volumes:
  #     - hadoop_datanode_3:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #   env_file:
  #     - ./hadoop.env
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: $NETWORK

volumes:
  hadoop_namenode:
  hadoop_srcfolder:
  hadoop_datanode_0:
  hadoop_datanode_1:
  hadoop_datanode_2:
  hadoop_datanode_3:
  atlas_conf:
    driver_opts:
      o: bind
      type: none
      device: $CONF_VOLUME
  atlas_data:
    driver_opts:
      o: bind
      type: none
      device: $DATA_VOLUME
  atlas_logs:
    driver_opts:
      o: bind
      type: none
      device: $LOGS_VOLUME
